### ISSUE TITLE
Booleannet Export errors

### ISSUE THREAD

**Issue by TillS** [matthiasbock/BooleSim#28]
When exporting the network to booleannet format, the network is deeply changed.
The problem appears to be a missing space when translating "!" into "not" when there are no parentheses (this time the parentheses are translated correctly from BoolNet to booleannet) but for instance !pluri_exo_meth or !pluri_exo_het_chrom becomes notpluri_exo_meth or notpluri_exo_het_chrom thus creating 2 new species. In python Booleannet, you have to introduce a space after the not!

**Comment by chaitan3** [comment]
@TillS, are you using the latest code? please do a git pull and retest, I had fixed this issue last week.

**Comment by TillS** [comment]
Weird...I just pulled it half an hour ago or so and the error was there. Now I pulled it again and it works. Maybe I forgot to update the browser or so. Cool! Just one minor thing: There is still some misplaced "falses" which give problems when exporting the network to booleannet, re-importing it and clicking on "rules" tab and back on "network" view which then shows the "false" node again. You think, this can still be corrected?

**Comment by chaitan3** [comment]
Should be fixed now. Damn, too many formats, code is getting a bit messy :P.

**Comment by TillS** [comment]
Just pulled it and tried several times. Unfortunately it doesn't work for me yet. When importing the .ginml demo file for the cell cycle, it still shows 2 wrong falses in the rule tab, which make trouble...

**Comment by chaitan3** [comment]
The  wrong false's are a bit difficult to avoid in the ginml import because of the complicated nature of the rules, they won't show up in the network view though. After exporting the file to python booleannet and importing it back into the simulator, the booleannet file simulates properly and there are no 'false' nodes.
